build(deps): bump @zip.js/zip.js from 2.7.73 to 2.8.2 (#1684)
* build(deps): bump @zip.js/zip.js from 2.7.73 to 2.8.2

Bumps [@zip.js/zip.js](https://github.com/gildas-lormeau/zip.js) from 2.7.73 to 2.8.2.
- [Release notes](https://github.com/gildas-lormeau/zip.js/releases)
- [Commits](https://github.com/gildas-lormeau/zip.js/compare/v2.7.73...v2.8.2)

---
updated-dependencies:
- dependency-name: "@zip.js/zip.js"
  dependency-version: 2.8.2
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* refactor(utils): fix TypeScript error in zip.ts

```
Error: src/utils/zip.ts(63,32): error TS2339: Property 'getData' does not exist on type 'Entry'.
  Property 'getData' does not exist on type 'DirectoryEntry'.
```

- https://github.com/gildas-lormeau/zip.js/issues/604
- https://github.com/gildas-lormeau/zip.js/discussions/602

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Mark <mark@remarkablemark.org>