test(cypress): fix write permission denied error in upload.feature
  1) Upload
       I can upload and delete a file:
     NotAllowedError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Failed to execute 'writeText' on 'Clipboard': Write permission denied.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.