refactor(utils): fix TypeScript error in zip.ts
```
Error: src/utils/zip.ts(63,32): error TS2339: Property 'getData' does not exist on type 'Entry'.
  Property 'getData' does not exist on type 'DirectoryEntry'.
```

- https://github.com/gildas-lormeau/zip.js/issues/604
- https://github.com/gildas-lormeau/zip.js/discussions/602